<?php

namespace Api\Helpers;

class ReservedWords
{
    private const WORDS = [
        'admin',
        'administrator',
        'api',
        'auth',
        'login',
        'logout',
        'register',
        'signup',
        'signin',
        'signout',
        'settings',
        'organizations',
        'users',
        'opensys',
        'dashboard',
        'profile',
        'home',
        'terms',
        'privacy',
        'help',
        'support',
        'contact',
        'about',
        'pricing',
        'features',
        'blog',
        'docs',
        'legal',
        'status',
        'app',
        'system',
        'public',
        'assets',
        'static',
        'dist',
        'vendor',
        'node_modules',
        'git',
        'env',
        'config',
        'database',
        'log',
        'logs',
        'cache',
        'temp',
        'tmp',
        'root',
        'super',
        'moderator',
        'bot',
        'crawler',
        'mail',
        'email',
        'smtp',
        'ftp',
        'ssh',
        'http',
        'https',
        'www',
        'web',
        'null',
        'undefined',
        'void',
        'true',
        'false',
    ];

    public static function isReserved(string $slug): bool
    {
        return in_array(strtolower(trim($slug)), self::WORDS);
    }
}
